### ISSUE TITLE
syntax question

### ISSUE THREAD

**Issue by saket424** [UnionPacific/udp-repeater#2]
@thomascoe 
what is the syntax for json if I want "all" packets received on 127.0.0.1:8001 from "any" port to be replicated to both 127.0.0.1:9000 and 127.0.0.1:9001 using some arbitrary transmit port ? I am confused my the map syntax and how that match criterion is specified. My traffic does not necessarily originate only from port 2000 or 2001 as specified in the example.json

Thanks in advance

**Comment by saket424** [comment]
This json worked!

{
    "listen" : [
        /* Ports and interfaces to listen on */
        {
            "id" : 2,
            "address" : "*",
            "port" : "8001"
        }
    ],
    "transmit" : [
        /* Ports and interfaces to bind to for transmitting */
        {
            "id" : 11,
            "address" : "*",
            "port" : "6000"
        }
    ],
    "target" : [
        /* Destination addresses and ports to send to */
        {
            "id" : 20,
            "address" : "127.0.0.1",
            "port" : "9000",
            "transmitter" : 11
        },
        {
            "id" : 21,
            "address" : "127.0.0.1",
            "port" : "9001",
            "transmitter" : 11
        }
    ],
    "map" : [
        /* Translation rules */
        {
            "source" : 2,
            "address" : "*",
            "port" : "*",
            "target" : [20,21]
        }
    ]
}

**Comment by thomascoe** [comment]
@saket424 Glad that worked! One thing you might consider, you may want to add 127.0.0.1 as the "address" for your listener if you want it to only forward packets received from other applications on the local host. As it is written now, it would forward on anything any other machine sends yours on that port.

You could also bind the transmitter to 127.0.0.1 as the address since you're only sending to local host as well, but that's not really necessary.

Also for the other places where you have an empty address specified, you may have to actually use a "*" instead to specify "any address"? I'd have to look through the parsing code later to be sure.
